name: Bug Report
description: File a bug report
title: "[Bug] "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Overview
      description: Please describe exactly what the bug is and what you expected to happen instead. Images/videos of it are always helpful.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce
      description: |
        Describe step by step, how to reproduce the bug.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: On which version of File Navigator did this bug appear? You can find the version in the header of the side bar.
    validations:
      required: true
  - type: input
    id: androidversion
    attributes:
      label: Android Version
      description: What is your Android Version? (i.e. Android 13)
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device Model
      description: What device do you use (i.e. Pixel 6)
    validations:
      required: true